### ISSUE TITLE
Incorrect error reporting of instant-apps - Felvin Search

### ISSUE THREAD

**Issue by FirePing32** [felvin-search/felvin.com-bugs#2]
## Screenshot(s)

<img width="988" alt="Screenshot 2022-02-08 at 11 24 45 AM" src="https://user-images.githubusercontent.com/43035576/152926885-a4be7cb4-e7fc-4a40-859f-290dbc425215.png">

## Affected search queries

This bug does not affect any search query. 

## Summary

The current error logging statements do not report the exact apps causing the problem.
```bash
Error: Request failed with status code 404 in [object Object]
```
I was going through the instant-apps repo, and found this renender file - https://github.com/felvin-search/instant-apps/blob/master/packages/sandbox/src/components/InstantAppsRenderer.tsx
I don't know if this is the same [renderer file](https://felvin.com/static/js/lib/renderer.tsx) used right now in felvin search, but looks similar to it.

## Environment

- Browser: Firefox Developer Edition (v97.0b5)
- Operating system: Mac OS Monterey

**Comment by FirePing32** [comment]
Update: The above error is logged when hitting this API. It gives 404 error.
<img width="612" alt="Screenshot 2022-02-08 at 12 05 50 PM" src="https://user-images.githubusercontent.com/43035576/152931997-04690130-db6f-45e3-a3ed-8f13e70ec60f.png">

**Comment by N-Shar-ma** [comment]
@FirePing32 Thanks for bringing this up. The instant app's name now shows up instead of `[object Object]`
![image](https://user-images.githubusercontent.com/68962290/152978269-643058af-f9d0-401d-a9cd-588cee5d9b08.png)

**Comment by FirePing32** [comment]
@N-Shar-ma Nice 💯. Closing this issue :)
